# Generated by Django 5.2.15 on 2026-06-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_computadora', models.CharField(default='Lenovo', max_length=100)),
                ('numero_equipo', models.CharField(max_length=50)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
    ]
