# Generated by Django 5.2.15 on 2026-06-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0001_initial'),
        ('Estudiante', '0001_initial'),
        ('Materia', '0001_initial'),
        ('Recurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hr_prestamo', models.DateTimeField(auto_now_add=True)),
                ('estado_prestamo', models.CharField(default='Activa', max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materia.materia')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recurso.recurso')),
            ],
        ),
    ]
